### PR TITLE
Fix issue #25: fix sphere rendering

### LINKED ISSUE #25: Sphere rendering
Spheres have some weird behaviour when rendered with the pathtracer: they appear split in half.

<p align="center">

</p>

### PR DESCRIPTION
**Pull request by ElisaLegnani**
This PR is meant to fix issue #25.

### CODE REVIEW

**Comment by ElisaLegnani** [comment]
Here some tests with diffusive sphere (0.5, 0.5, 0.5) and emittive background (0, 0, 1) and ground (1, 0, 0), with antialiasing applied (number of samples per pixel = 4), to better see the effect.

There must be an approximation problem when calculating the ray intersection with the sphere close to the equatorial line.

<p align="center">

</p>

**Comment by ElisaLegnani** [comment]
The issue appears only when scaling the sphere along the x direction!
*Note*: the previuos images where obtained by scaling the sphere along all directions.


<p align="center">

 <br>
 <em>scaling along x (0.6)</em>
</p>

<p align="center">

 <br>
 <em>scaling along y (0.6)</em>
</p>

<p align="center">

 <br>
 <em>scaling along z (0.6)</em>
</p>

<p align="center">

 <br>
 <em>no scaling</em>
</p>

**Comment by ElisaLegnani** [comment]
It has nothing to do neither with scaling nor with spheres! Normals of the world's light rays - shapes intersections are not normalized, and they need to be for diffusive BRDF ray scattering.

**Comment by ElisaLegnani** [comment]
Bug fixed!
<p align="center">

 <br>
 <em>scaling along x (0.6)</em>
</p>

**Comment by ElisaLegnani** [comment]
A control on normalization of vectors/normals for ONB creation could be useful!

**Comment by adelezaini** [comment]
That is a great idea! So anyone who wants to enhance or play with the code is advised if the ONB creation doesn't work as it should.

**Pull request merged**
